## mpv-coverart 配置文件
## 此文件包含脚本的所有默认选项

# 有效封面图片的名称列表，必须用分号分隔，不能有空格
# 脚本不区分大小写
# 加载任何具有有效名称和有效图像扩展名的文件
# 如果设置为空，则会加载任何名称的图像文件（但强烈建议不要和 imageExts 同时留空）
names=cover;folder;album;front

# 有效的图像扩展名，语法同 names 选项
# 如果留空，将加载所有类型的文件（只要文件名匹配）
# 强烈建议不要将这两个列表都留空 —— 会导致非图片文件被误加载为封面
imageExts=jpg;jpeg;png;bmp;gif;webp

# 默认情况下，只有检测到文件是音频文件时才会加载封面
# 音频文件是指 MPV 报告第一个流为音频或专辑封面的文件
always_scan_coverart=no

# 如果为 false (no)，在找到一个有效文件后就会停止寻找封面
# 并且如果文件本身已经包含内置封面，也不会再查找外部封面
load_extra_files=yes

# 如果未找到封面图片，使用的占位符图片的文件路径
# 仅在 force-window (强制窗口) 启用时使用
# 如果留空，则相当于禁用此功能
placeholder=

# 是否在文件系统中搜索有效的封面图片
load_from_filesystem=yes

# 是否在当前播放列表中搜索有效的封面图片
# 这看起来可能没啥用，但对于从 MPV 无法扫描的网络文件服务器流式传输时很有用
# 此条目会导致脚本始终搜索播放列表
# 关于默认行为的描述，请参阅下方的 README 说明
load_from_playlist=no

# 在预加载阶段同步加载封面图片（在文件加载后，
# 但在播放开始或轨道选择之前）
# 这在实践中意味着：
#  - MPV 播放器在所有封面加载完成前不会开始播放
#  - 这意味着在慢速文件系统/网络系统上，播放可能会延迟
#  - 控制台不会打印 "track added" (轨道已添加) 消息
#  - 支持 --vid=x 属性，因为 MPV 不会在封面加载完成前尝试选择 x
#  - "稍后观看" (watch-later) 会记住视频是在哪个封面上
#  - 避免了每个文件开始时从黑色无视频画面切换到封面的尴尬闪烁 (force-window=yes)
#  - 从终端播放时，窗口不会在文件之间关闭和重新打开 (force-window=no)
#  - 默认情况下会加载外部封面而不是嵌入图像（参见下文更改此行为）
#  - 可能提供与其他脚本更好的兼容性
preload=no

# 告诉 MPV 将给定的视频作为专辑封面加载，这提供了一些优化，
# 并使封面的行为更像嵌入式专辑封面
# 这仅在 MPV v0.34 (尚未发布) 中可用
# 此选项强制执行 prefer_embedded (优先嵌入)
use_albumart_flag=no

# 当 preload=true 时，优先选择嵌入的视频轨道，而不是新的外部文件
# 默认情况下，MPV 会优先选择外部视频轨道
# 此设置强制播放第一个嵌入的文件
# 具体来说，此选项只是在 auto 模式下将 --vid 设置为 1
prefer_embedded=no