### 文档_ https://github.com/hooke007/mpv_PlayKit/blob/main/portable_config/script-opts.conf

##⇘⇘脚本选项


##########
# 控制台 #
##########

 script-opts-append = console-monospace_font=monospace                # 指定控制台的字体，monospace=系统等宽字体，避免非中文环境缺字体
 script-opts-append = console-font_size=12                             # 字体大小（select 菜单用）
 script-opts-append = console-border_size=0.6                          # 字体边框宽度
 script-opts-append = console-margin_x=-1                              # 左边距和底边距（值 -1 表示和mpv选项 --osd-margin-x 一致）
 script-opts-append = console-margin_y=-1
 script-opts-append = console-scale_with_window=auto                   # <yes|no|默认auto> 是否根据窗口高度缩放控制台。值 auto 表示和mpv选项 --osd-scale-by-window 一致

 script-opts-append = console-history_dedup=yes                        # 移除历史记录中的重复条目，只保留最新的一项，默认 yes
 script-opts-append = console-font_hw_ratio=auto                       # 字体高宽比，影响“补全提示区”的尺寸（建议取值范围 1.8~2.5），默认 auto


#############
# OSD命令行 #
#############

#script-opts-append = commands-persist_history=yes
 script-opts-append = commands-history_path=~~/_cache/command_history.txt


############
# 统计数据 #
############

 script-opts-append = stats-duration=2
 script-opts-append = stats-redraw_delay=0.5
 script-opts-append = stats-persistent_overlay=yes
 script-opts-append = stats-filter_params_max_length=1


########
# YTDL #
########

#script-opts-append = ytdl_hook-try_ytdl_first=yes

#script-opts-append = ytdl_hook-exclude="%.avi$|%.flv$|%.m3u$|%.m3u8$|%.m4v$|%.mkv$|%.mp4$|%.ts$|%.VOB$|%.webm$|%.wmv$"
#script-opts-append = ytdl_hook-use_manifests=yes

####################
# 全局属性保存恢复 #
####################

#script-opts-append = save_global_props-save_mode=0
 script-opts-append = save_global_props-props=volume,mute
#script-opts-append = save_global_props-cache_dir=~~/_cache/


################
# MediaInfo版统计数据 #
################

 script-opts-append = "stats_mediainfo-mediainfo_path=~~/MediaInfo.exe"
 script-opts-append = "stats_mediainfo-font_mono=monospace"
