import "DiscType.idl";

namespace mpv_winrt
{
    runtimeclass MpvPreviewer
    {
        MpvPreviewer();

        Windows.Foundation.IAsyncAction Initialize(Microsoft.UI.Xaml.Controls.Image image, UInt32 width, UInt32 height);
        void Destroy();

        void LoadFile(String url);
        void SetPosition(Double position);
        void Pause();

        void SetEdition(Int32 edition);
        void SetDiscPath(DiscType type, String path);
        void SetVideoTrack(Int32 value);
    };
}