namespace mpv_winrt
{
	runtimeclass MpvPlaylistItem
	{
		Int32 Id { get; };
		Int32 Index { get; };
		String Filename { get; };
		String Title { get; };
		Boolean IsCurrent { get; };
		Boolean IsPlaying { get; };
		Double Duration { get; };
	};
}
