import "DisplayColorKind.idl";
import "MpvLogEventArgs.idl";
import "MpvPlaylistItem.idl";
import "MpvChapter.idl";
import "MpvEdition.idl";
import "MpvAudioDevice.idl";
import "MpvGpuAdapter.idl";
import "MpvProfile.idl";
import "MpvMenuItem.idl";
import "MpvTrack.idl";
import "MpvPreviewInfo.idl";
import "PlaybackStateChangedEventArgs.idl";
import "VolumeChangedEventArgs.idl";
import "PositionChangedEventArgs.idl";
import "SpeedChangedEventArgs.idl";
import "MediaInfoChangedEventArgs.idl";
import "PlaybackFailedEventArgs.idl";
import "WindowChangedEventArgs.idl";

namespace mpv_winrt
{
    delegate void MediaLoadedEventHandler();
    delegate void PlaybackEndedEventHandler();
    delegate void PlaybackFailedEventHandler(PlaybackFailedEventArgs args);
    delegate void SeekEventHandler();
    delegate void FileLoadedEventHandler();

    delegate void PlaybackStateChangedEventHandler(PlaybackStateChangedEventArgs args);
    delegate void VolumeChangedEventHandler(VolumeChangedEventArgs args);
    delegate void PositionChangedEventHandler(PositionChangedEventArgs args);
    delegate void SpeedChangedEventHandler(SpeedChangedEventArgs args);
    delegate void MediaInfoChangedEventHandler(MediaInfoChangedEventArgs args);
    delegate void VoConfiguredEventHandler();
    delegate void WindowChangedEventHandler(WindowChangedEventArgs args);
    delegate void LoopFileChangedEventHandler();
    delegate void LoopPlaylistChangedEventHandler();
    delegate void ShuffleChangedEventHandler();
    delegate void PlaylistChangedEventHandler();
    delegate void PreviewChangedEventHandler(MpvPreviewInfo args);
    delegate void MpvLogEventHandler(MpvLogEventArgs args);
    delegate void MpvPropertyChangedEventHandler(String name, String value);

    runtimeclass MpvPlayer
    {
        MpvPlayer();
        void Initialize(String configPath, UInt32 width, UInt32 height, Int32 volume, DisplayColorKind colorKind, Int32 refreshRate);
        void Destroy();
        void UpdateSize(UInt32 width, UInt32 height);
        void LoadFile(String url, Double position);
        void LoadList(String url);
        void AttachSwapChain(Microsoft.UI.Xaml.Controls.SwapChainPanel panel);
        void UpdateSwapChainScale(Single scaleX, Single scaleY);
        void UpdateDisplayColorInfo(DisplayColorKind colorKind);
        void UpdateDisplayRefreshRate(Int32 refreshRate);

        void Play();
        void Pause();
        void Stop();
        void TogglePlayPause();
        Boolean IsPaused();

        void Command(Windows.Foundation.Collections.IVector<String> args);
        void CommandString(String cmd);
        void ApplyCommandStrings(Windows.Foundation.Collections.IVector<String> commands);

        void SetLogLevel(String level);

        String GetWatchHistoryPath();
        String GetWatchLaterFolderPath();
        String GetCurrentFilePath();
        Boolean SaveWatchHistory();

        Double Volume();
        void Volume(Double value);
        Boolean IsMuted();
        void IsMuted(Boolean value);

        Double Position();
        void Position(Double value);
        Double Duration();

        Double AbLoopA();
        Double AbLoopB();

        Int32 CurrentVideoTrack();
        void CurrentVideoTrack(Int32 value);
        Int32 CurrentAudioTrack();
        void CurrentAudioTrack(Int32 value);
        Int32 CurrentSubtitleTrack();
        void CurrentSubtitleTrack(Int32 value);
        Int32 CurrentSecondSubtitleTrack();
        void CurrentSecondSubtitleTrack(Int32 value);

        void AddSubtitle(String url, Boolean selected, String title);

        Double PlaybackSpeed();
        void PlaybackSpeed(Double value);

        Boolean LoopFile();
        void LoopFile(Boolean enabled);
        void SetLoopPlaylist(Boolean enabled);
        Boolean LoopPlaylist();
        void SetShuffle(Boolean enabled);
        Boolean Shuffle();

        void SetAspectRatio(String ratio);

        void SetHoverSec(Double sec);
        void SetDrawPreview(Int32 x, Int32 y, Int32 w, Int32 h);
        void ClearPreview();

        Windows.Foundation.Collections.IVectorView<MpvPlaylistItem> GetPlaylist();

        Windows.Foundation.Collections.IVectorView<MpvTrack> GetAudioTracks();
        Windows.Foundation.Collections.IVectorView<MpvTrack> GetVideoTracks();
        Windows.Foundation.Collections.IVectorView<MpvTrack> GetSubtitleTracks();
        Windows.Foundation.Collections.IVectorView<MpvChapter> GetChapters();
        Windows.Foundation.Collections.IVectorView<MpvEdition> GetEditions();
        Windows.Foundation.Collections.IVectorView<MpvAudioDevice> GetAudioDevices();
        Windows.Foundation.Collections.IVectorView<MpvGpuAdapter> GetGpuAdapters();
        Windows.Foundation.Collections.IVectorView<MpvProfile> GetProfiles();
        Int32 CurrentChapter();
        Int32 CurrentEdition();

        Windows.Foundation.Collections.IVectorView<MpvMenuItem> GetMenu();
        String GetSubtitleExtensions();

        event MediaLoadedEventHandler MediaLoaded;
        event PlaybackEndedEventHandler PlaybackEnded;
        event PlaybackFailedEventHandler PlaybackFailed;
        event SeekEventHandler Seeked;
        event FileLoadedEventHandler FileLoaded;

        event PlaybackStateChangedEventHandler PlaybackStateChanged;
        event VolumeChangedEventHandler VolumeChanged;
        event PositionChangedEventHandler PositionChanged;
        event SpeedChangedEventHandler SpeedChanged;
        event MediaInfoChangedEventHandler MediaInfoChanged;
        event VoConfiguredEventHandler VoConfigured;
        event WindowChangedEventHandler WindowChanged;
        event LoopFileChangedEventHandler LoopFileChanged;
        event LoopPlaylistChangedEventHandler LoopPlaylistChanged;
        event ShuffleChangedEventHandler ShuffleChanged;
        event PlaylistChangedEventHandler PlaylistChanged;
        event PreviewChangedEventHandler PreviewChanged;
        event MpvLogEventHandler LogMessage;
    };
}
