using System;
using System.IO;

namespace mpv_winui.Modules.Settings;

/// <summary>
/// 设置项 → mpv 命令 的映射：设置页改动时即时下发，播放器初始化后批量应用。
/// </summary>
public static class MpvSettings
{
    /// <summary>
    /// Quote a value for mpv's command string parser. mpv_command_string uses
    /// C-style escapes inside quotes, so Windows paths must have their
    /// backslashes doubled, otherwise "C:\Users\..." fails to parse and the
    /// option silently keeps its previous value.
    /// </summary>
    private static string Q(string value) =>
        $"\"{value.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";

    public static string? ToCommand(string key, object value)
    {
        return key switch
        {
            nameof(AppSettings.Hwdec) => $"set hwdec {value}",
            nameof(AppSettings.HwdecCodecs) => $"set hwdec-codecs {(string)value}",
            nameof(AppSettings.AlwaysOnTop) => $"set ontop {(value is true ? "yes" : "no")}",
            nameof(AppSettings.InputIme) => $"set input-ime {(value is true ? "yes" : "no")}",
            nameof(AppSettings.D3d11OutputCsp) => string.IsNullOrWhiteSpace((string)value) ? null : $"set d3d11-output-csp {(string)value}",
            nameof(AppSettings.D3d11ExclusiveFs) => $"set d3d11-exclusive-fs {(value is true ? "yes" : "no")}",
            nameof(AppSettings.D3d11Flip) => $"set d3d11-flip {(value is true ? "yes" : "no")}",
            nameof(AppSettings.D3d11Adapter) => string.IsNullOrWhiteSpace((string)value) ? null : $"set d3d11-adapter {Q((string)value)}",
            nameof(AppSettings.VolumeMax) => $"set volume-max {value}",
            nameof(AppSettings.KeepOpen) => $"set keep-open {value}",
            nameof(AppSettings.LoopPlaylist) => $"set loop-playlist {value}",
            nameof(AppSettings.LoopFile) => $"set loop-file {(value is true ? "inf" : "no")}",
            nameof(AppSettings.Volume) => $"set volume {value}",
            nameof(AppSettings.CacheEnabled) => $"set cache {(string)value}",
            nameof(AppSettings.DemuxerReadahead) => $"set demuxer-readahead-secs {(double)value}",
            nameof(AppSettings.Ytdl) => $"set ytdl {(value is true ? "yes" : "no")}",
            nameof(AppSettings.YtdlRawOptionsAppend) => string.IsNullOrWhiteSpace((string)value) ? null : $"set ytdl-raw-options-append {Q((string)value)}",
            nameof(AppSettings.YtdlFormat) => string.IsNullOrWhiteSpace((string)value) ? null : $"set ytdl-format {Q((string)value)}",
            nameof(AppSettings.UserAgent) => string.IsNullOrWhiteSpace((string)value) ? null : $"set user-agent {Q((string)value)}",
            nameof(AppSettings.Referrer) => string.IsNullOrWhiteSpace((string)value) ? null : $"set referrer {Q((string)value)}",
            nameof(AppSettings.HttpHeaderFields) => string.IsNullOrWhiteSpace((string)value) ? null : $"set http-header-fields {Q((string)value)}",
            nameof(AppSettings.HttpProxy) => string.IsNullOrWhiteSpace((string)value) ? null : $"set http-proxy {Q((string)value)}",
            nameof(AppSettings.CookiesFile) => string.IsNullOrWhiteSpace((string)value) ? null : $"set cookies-file {Q((string)value)}",
            nameof(AppSettings.TlsVerify) => $"set tls-verify {(value is true ? "yes" : "no")}",
            nameof(AppSettings.NetworkTimeout) => $"set network-timeout {value}",
            nameof(AppSettings.CurlMaxRedirects) => $"set curl-max-redirects {value}",
            nameof(AppSettings.CurlMaxRetries) => $"set curl-max-retries {value}",
            nameof(AppSettings.CurlConnectTimeout) => $"set curl-connect-timeout {value}",
            nameof(AppSettings.CurlBufferSize) => $"set curl-buffer-size {value}",
            nameof(AppSettings.CurlMaxRequestSize) => $"set curl-max-request-size {value}",
            nameof(AppSettings.AutoCreatePlaylist) => $"set autocreate-playlist {(string)value}",
            nameof(AppSettings.DirectoryMode) => $"set directory-mode {(string)value}",
            nameof(AppSettings.DirectoryFilterTypes) => $"set directory-filter-types {(string)value}",
            nameof(AppSettings.VideoExts) => $"set video-exts {(string)value}",
            nameof(AppSettings.ImageExts) => $"set image-exts {(string)value}",
            nameof(AppSettings.AudioExts) => $"set audio-exts {(string)value}",
            nameof(AppSettings.InputIpcServer) => string.IsNullOrWhiteSpace((string)value) ? null : $"set input-ipc-server {Q((string)value)}",
            nameof(AppSettings.CacheDirectory) => string.IsNullOrWhiteSpace((string)value) ? null : $"set cache-dir {Q((string)value)}",
            nameof(AppSettings.WatchLaterDir) => string.IsNullOrWhiteSpace((string)value) ? null : $"set watch-later-dir {Q((string)value)}",
            nameof(AppSettings.WatchLaterOptions) => string.IsNullOrWhiteSpace((string)value) ? null : $"set watch-later-options {(string)value}",
            nameof(AppSettings.IccCacheDir) => string.IsNullOrWhiteSpace((string)value) ? null : $"set icc-cache-dir {Q((string)value)}",
            nameof(AppSettings.GpuShaderCacheDir) => string.IsNullOrWhiteSpace((string)value) ? null : $"set gpu-shader-cache-dir {Q((string)value)}",
            nameof(AppSettings.Deinterlace) => $"set deinterlace {value}",
            nameof(AppSettings.AspectRatio) => $"set video-aspect-override {value}",
            nameof(AppSettings.Cscale) => $"set cscale {(string)value}",
            nameof(AppSettings.Tscale) => $"set tscale {(string)value}",
            nameof(AppSettings.LinearUpscaling) => $"set linear-upscaling {(value is true ? "yes" : "no")}",
            nameof(AppSettings.Dither) => $"set dither {(string)value}",
            nameof(AppSettings.Panscan) => $"set panscan {(double)value}",
            nameof(AppSettings.VideoUnscaled) => string.IsNullOrWhiteSpace((string)value) ? null : $"set video-unscaled {(string)value}",
            nameof(AppSettings.BackgroundTileColor0) => string.IsNullOrWhiteSpace((string)value) ? null : $"set background-tile-color-0 {Q((string)value)}",
            nameof(AppSettings.BackgroundTileColor1) => string.IsNullOrWhiteSpace((string)value) ? null : $"set background-tile-color-1 {Q((string)value)}",
            nameof(AppSettings.BackgroundTileSize) => $"set background-tile-size {(int)value}",
            nameof(AppSettings.SubFontSize) => $"set sub-font-size {value}",
            nameof(AppSettings.SubDelay) => $"set sub-delay {value}",
            nameof(AppSettings.Speed) => $"set speed {value}",
            nameof(AppSettings.SubPos) => $"set sub-pos {value}",
            nameof(AppSettings.AudioLanguage) => string.IsNullOrWhiteSpace((string)value) ? null : $"set alang {(string)value}",
            nameof(AppSettings.SubtitleLanguage) => string.IsNullOrWhiteSpace((string)value) ? null : $"set slang {(string)value}",
            nameof(AppSettings.SubFilePaths) => string.IsNullOrWhiteSpace((string)value) ? null : $"set sub-file-paths {Q((string)value)}",
            nameof(AppSettings.SubHdrPeak) => $"set sub-hdr-peak {(int)value}",
            nameof(AppSettings.ImageSubsHdrPeak) => $"set image-subs-hdr-peak {(int)value}",
            nameof(AppSettings.ImageSubsVideoResolution) => $"set image-subs-video-resolution {(value is true ? "yes" : "no")}",
            nameof(AppSettings.SubAssStyleOverrides) => string.IsNullOrWhiteSpace((string)value) ? null : $"set sub-ass-style-overrides {Q((string)value)}",
            nameof(AppSettings.SubColor) => string.IsNullOrWhiteSpace((string)value) ? null : $"set sub-color {Q((string)value)}",
            nameof(AppSettings.SubBackColor) => string.IsNullOrWhiteSpace((string)value) ? null : $"set sub-back-color {Q((string)value)}",
            nameof(AppSettings.SubBorderColor) => string.IsNullOrWhiteSpace((string)value) ? null : $"set sub-border-color {Q((string)value)}",
            nameof(AppSettings.SubScaleSigns) => $"set sub-scale-signs {(value is true ? "yes" : "no")}",
            nameof(AppSettings.SubAssUseVideoData) => string.IsNullOrWhiteSpace((string)value) ? null : $"set sub-ass-use-video-data {(string)value}",
            nameof(AppSettings.SubAssVideoAspectOverride) => string.IsNullOrWhiteSpace((string)value) ? null : $"set sub-ass-video-aspect-override {(string)value}",
            nameof(AppSettings.SubAssVsfilterColorCompat) => string.IsNullOrWhiteSpace((string)value) ? null : $"set sub-ass-vsfilter-color-compat {(string)value}",
            nameof(AppSettings.AudioDevice) => string.IsNullOrWhiteSpace((string)value) ? null : $"set audio-device {(string)value}",
            nameof(AppSettings.ScreenshotDirectory) => string.IsNullOrWhiteSpace((string)value) ? null : $"set screenshot-directory {Q((string)value)}",
            nameof(AppSettings.ScreenshotTemplate) => string.IsNullOrWhiteSpace((string)value) ? null : $"set screenshot-template {(string)value}",
            nameof(AppSettings.SavePositionOnQuit) => $"set save-position-on-quit {(value is true ? "yes" : "no")}",
            nameof(AppSettings.ResumePlayback) => $"set resume-playback {(value is true ? "yes" : "no")}",
            nameof(AppSettings.ScreenshotFormat) => $"set screenshot-format {(string)value}",
            nameof(AppSettings.ScreenshotJpegQuality) => $"set screenshot-jpeg-quality {value}",
            nameof(AppSettings.ScreenshotJpegSourceChroma) => $"set screenshot-jpeg-source-chroma {(value is true ? "yes" : "no")}",
            nameof(AppSettings.VideoSync) => $"set video-sync {(string)value}",
            nameof(AppSettings.VideoSyncMaxVideoChange) => $"set video-sync-max-video-change {(int)value}",
            nameof(AppSettings.Interpolation) => $"set interpolation {(value is true ? "yes" : "no")}",
            nameof(AppSettings.CorrectDownscaling) => $"set correct-downscaling {(value is true ? "yes" : "no")}",
            nameof(AppSettings.Scale) => $"set scale {(string)value}",
            nameof(AppSettings.DScale) => $"set dscale {(string)value}",
            nameof(AppSettings.VideoRotate) => $"set video-rotate {(string)value}",
            nameof(AppSettings.Deband) => $"set deband {(value is true ? "yes" : "no")}",
            nameof(AppSettings.LinearDownscaling) => $"set linear-downscaling {(value is true ? "yes" : "no")}",
            nameof(AppSettings.SigmoidUpscaling) => $"set sigmoid-upscaling {(value is true ? "yes" : "no")}",
            nameof(AppSettings.ToneMapping) => $"set tone-mapping {(string)value}",
            nameof(AppSettings.DitherDepth) => $"set dither-depth {(string)value}",
            nameof(AppSettings.HrSeek) => $"set hr-seek {(value is true ? "yes" : "no")}",
            nameof(AppSettings.HrSeekFramedrop) => $"set hr-seek-framedrop {(value is true ? "yes" : "no")}",
            nameof(AppSettings.CacheOnDisk) => $"set cache-on-disk {(value is true ? "yes" : "no")}",
            nameof(AppSettings.TargetColorspaceHint) => $"set target-colorspace-hint {(string)value}",
            nameof(AppSettings.TargetColorspaceHintMode) => string.IsNullOrWhiteSpace((string)value) ? null : $"set target-colorspace-hint-mode {(string)value}",
            nameof(AppSettings.TargetColorspaceHintStrict) => $"set target-colorspace-hint-strict {(value is true ? "yes" : "no")}",
            nameof(AppSettings.TargetPrim) => string.IsNullOrWhiteSpace((string)value) ? null : $"set target-prim {(string)value}",
            nameof(AppSettings.TargetTrc) => string.IsNullOrWhiteSpace((string)value) ? null : $"set target-trc {(string)value}",
            nameof(AppSettings.TargetPeak) => (value is int peak && peak > 0) ? $"set target-peak {peak}" : null,
            nameof(AppSettings.GamutMappingMode) => string.IsNullOrWhiteSpace((string)value) ? null : $"set gamut-mapping-mode {(string)value}",
            nameof(AppSettings.VideoOutputLevels) => $"set video-output-levels {(string)value}",
            nameof(AppSettings.VideoDecodeDirect) => $"set vd-lavc-dr {(string)value}",
            nameof(AppSettings.IccProfileAuto) => $"set icc-profile-auto {(value is true ? "yes" : "no")}",
            nameof(AppSettings.IccProfile) => string.IsNullOrWhiteSpace((string)value) ? null : $"set icc-profile {Q((string)value)}",
            nameof(AppSettings.IccForceContrast) => (value is int contrast && contrast > 0) ? $"set icc-force-contrast {contrast}" : null,
            nameof(AppSettings.IccCache) => $"set icc-cache {(value is true ? "yes" : "no")}",
            nameof(AppSettings.Icc3dlutSize) => $"set icc-3dlut-size {(string)value}",
            nameof(AppSettings.DemuxerMaxBytes) => $"set demuxer-max-bytes {(int)value}MiB",
            nameof(AppSettings.DemuxerMaxBackBytes) => (value is int back && back > 0) ? $"set demuxer-max-back-bytes {back}MiB" : null,
            nameof(AppSettings.GpuShaderCache) => $"set gpu-shader-cache {(value is true ? "yes" : "no")}",
            nameof(AppSettings.GlslShadersAppend) => string.IsNullOrWhiteSpace((string)value) ? null : $"set glsl-shaders-append {Q((string)value)}",
            nameof(AppSettings.AudioChannels) => $"set audio-channels {(string)value}",
            nameof(AppSettings.AudioGapless) => $"set audio-gapless {(string)value}",
            nameof(AppSettings.AudioWaitOpen) => $"set audio-wait-open {(value is true ? "yes" : "no")}",
            nameof(AppSettings.AudioBuffer) => (value is int buf && buf > 0) ? $"set audio-buffer {buf}" : null,
            nameof(AppSettings.AudioExclusive) => $"set audio-exclusive {(value is true ? "yes" : "no")}",
            nameof(AppSettings.AudioPitchCorrection) => $"set audio-pitch-correction {(value is true ? "yes" : "no")}",
            nameof(AppSettings.AudioNormalizeDownmix) => $"set audio-normalize-downmix {(value is true ? "yes" : "no")}",
            nameof(AppSettings.AudioFileAuto) => $"set audio-file-auto {(string)value}",
            nameof(AppSettings.AudioFilePaths) => string.IsNullOrWhiteSpace((string)value) ? null : $"set audio-file-paths {Q((string)value)}",
            nameof(AppSettings.AudioDisplay) => $"set audio-display {(string)value}",
            nameof(AppSettings.AudioDelay) => $"set audio-delay {value}",
            nameof(AppSettings.SubAssOverride) => $"set sub-ass-override {(string)value}",
            nameof(AppSettings.SubBlur) => $"set sub-blur {value}",
            nameof(AppSettings.SubAuto) => $"set sub-auto {(string)value}",
            nameof(AppSettings.SubFont) => string.IsNullOrWhiteSpace((string)value) ? null : $"set sub-font {Q((string)value)}",
            nameof(AppSettings.SubFontProvider) => $"set sub-font-provider {(string)value}",
            nameof(AppSettings.SubFontFile) => value is string fontFile && !string.IsNullOrWhiteSpace(fontFile)
                ? $"set sub-fonts-dir {Q(Path.GetDirectoryName(fontFile) ?? fontFile)}"
                : null,
            nameof(AppSettings.SubAssScaleWithWindow) => $"set sub-ass-scale-with-window {(value is true ? "yes" : "no")}",
            nameof(AppSettings.BlendSubtitles) => $"set blend-subtitles {(string)value}",
            nameof(AppSettings.SubFallback) => $"set subs-fallback {(string)value}",
            nameof(AppSettings.SubCodePage) => $"set sub-codepage {(string)value}",
            nameof(AppSettings.SubOutlineSize) => $"set sub-outline-size {value}",
            nameof(AppSettings.SubShadowOffset) => $"set sub-shadow-offset {value}",
            nameof(AppSettings.SubEmbeddedFonts) => $"set embeddedfonts {(value is true ? "yes" : "no")}",
            nameof(AppSettings.SubUseMargins) => $"set sub-use-margins {(value is true ? "yes" : "no")}",
            nameof(AppSettings.SubAssForceMargins) => $"set sub-ass-force-margins {(value is true ? "yes" : "no")}",
            nameof(AppSettings.StretchImageSubsToScreen) => $"set stretch-image-subs-to-screen {(value is true ? "yes" : "no")}",
            nameof(AppSettings.OsdFontSize) => $"set osd-font-size {value}",
            nameof(AppSettings.OsdFont) => string.IsNullOrWhiteSpace((string)value) ? null : $"set osd-font {Q((string)value)}",
            nameof(AppSettings.OsdColor) => string.IsNullOrWhiteSpace((string)value) ? null : $"set osd-color {Q((string)value)}",
            nameof(AppSettings.OsdOutlineColor) => string.IsNullOrWhiteSpace((string)value) ? null : $"set osd-outline-color {Q((string)value)}",
            nameof(AppSettings.OsdPlayingMsg) => AppContext.AppSetting.ShowOsdPlayingMsg
                ? (string.IsNullOrWhiteSpace((string)value) ? null : $"set osd-playing-msg {Q((string)value)}")
                : "set osd-playing-msg \"\"",
            nameof(AppSettings.OsdPlayingMsgDuration) => $"set osd-playing-msg-duration {(int)value}",
            nameof(AppSettings.OsdBarWidth) => $"set osd-bar-w {(int)value}",
            nameof(AppSettings.OsdBarHeight) => $"set osd-bar-h {(double)value}",
            nameof(AppSettings.OsdBlur) => $"set osd-blur {(double)value}",
            nameof(AppSettings.OsdOutlineSize) => $"set osd-outline-size {(double)value}",
            nameof(AppSettings.OsdFractions) => $"set osd-fractions {(value is true ? "yes" : "no")}",
            nameof(AppSettings.OsdOnSeek) => $"set osd-on-seek {(string)value}",
            nameof(AppSettings.OsdDuration) => $"set osd-duration {value}",
            nameof(AppSettings.CacheSecs) => (value is int n && n > 0) ? $"set cache-secs {n}" : null,
            nameof(AppSettings.ScreenshotPngCompression) => $"set screenshot-png-compression {value}",
            nameof(AppSettings.ScreenshotPngFilter) => $"set screenshot-png-filter {(int)value}",
            nameof(AppSettings.ScreenshotWebpQuality) => $"set screenshot-webp-quality {value}",
            nameof(AppSettings.ScreenshotWebpLossless) => $"set screenshot-webp-lossless {(value is true ? "yes" : "no")}",
            nameof(AppSettings.ScreenshotWebpCompression) => $"set screenshot-webp-compression {(int)value}",
            nameof(AppSettings.ScreenshotJxlDistance) => $"set screenshot-jxl-distance {(int)value}",
            nameof(AppSettings.ScreenshotJxlEffort) => $"set screenshot-jxl-effort {(int)value}",
            nameof(AppSettings.ScreenshotAvifEncoder) => string.IsNullOrWhiteSpace((string)value) ? null : $"set screenshot-avif-encoder {Q((string)value)}",
            nameof(AppSettings.ScreenshotHighBitDepth) => $"set screenshot-high-bit-depth {(value is true ? "yes" : "no")}",
            nameof(AppSettings.ScreenshotTagColorspace) => $"set screenshot-tag-colorspace {(value is true ? "yes" : "no")}",
            nameof(AppSettings.ScreenshotSw) => $"set screenshot-sw {(value is true ? "yes" : "no")}",
            nameof(AppSettings.VsrAutoEnabled) => $"set user-data/mpvw/vsr-auto {(value is true ? "yes" : "no")}",
            nameof(AppSettings.HdrAutoMode) => $"script-message-to hdr_auto mode {(string)value}",
            nameof(AppSettings.SeekHoldEnabled) => $"set user-data/mpvw/seek-hold {(value is true ? "yes" : "no")}",
            _ => null,
        };
    }

    public static void ApplyAll(Action<string> run)
    {
        var s = AppContext.AppSetting;
        foreach (var (key, value) in new (string, object)[]
        {
            (nameof(AppSettings.Hwdec), s.Hwdec),
            (nameof(AppSettings.HwdecCodecs), s.HwdecCodecs),
            (nameof(AppSettings.AlwaysOnTop), s.AlwaysOnTop),
            (nameof(AppSettings.InputIme), s.InputIme),
            (nameof(AppSettings.D3d11OutputCsp), s.D3d11OutputCsp),
            (nameof(AppSettings.D3d11ExclusiveFs), s.D3d11ExclusiveFs),
            (nameof(AppSettings.D3d11Flip), s.D3d11Flip),
            (nameof(AppSettings.D3d11Adapter), s.D3d11Adapter),
            (nameof(AppSettings.VolumeMax), s.VolumeMax),
            (nameof(AppSettings.KeepOpen), s.KeepOpen),
            (nameof(AppSettings.LoopPlaylist), s.LoopPlaylist),
            (nameof(AppSettings.LoopFile), s.LoopFile),
            (nameof(AppSettings.Volume), s.Volume),
            (nameof(AppSettings.CacheEnabled), s.CacheEnabled),
            (nameof(AppSettings.DemuxerReadahead), s.DemuxerReadahead),
            (nameof(AppSettings.Ytdl), s.Ytdl),
            (nameof(AppSettings.YtdlRawOptionsAppend), s.YtdlRawOptionsAppend),
            (nameof(AppSettings.YtdlFormat), s.YtdlFormat),
            (nameof(AppSettings.UserAgent), s.UserAgent),
            (nameof(AppSettings.Referrer), s.Referrer),
            (nameof(AppSettings.HttpHeaderFields), s.HttpHeaderFields),
            (nameof(AppSettings.HttpProxy), s.HttpProxy),
            (nameof(AppSettings.CookiesFile), s.CookiesFile),
            (nameof(AppSettings.TlsVerify), s.TlsVerify),
            (nameof(AppSettings.NetworkTimeout), s.NetworkTimeout),
            (nameof(AppSettings.CurlMaxRedirects), s.CurlMaxRedirects),
            (nameof(AppSettings.CurlMaxRetries), s.CurlMaxRetries),
            (nameof(AppSettings.CurlConnectTimeout), s.CurlConnectTimeout),
            (nameof(AppSettings.CurlBufferSize), s.CurlBufferSize),
            (nameof(AppSettings.CurlMaxRequestSize), s.CurlMaxRequestSize),
            (nameof(AppSettings.AutoCreatePlaylist), s.AutoCreatePlaylist),
            (nameof(AppSettings.DirectoryMode), s.DirectoryMode),
            (nameof(AppSettings.DirectoryFilterTypes), s.DirectoryFilterTypes),
            (nameof(AppSettings.VideoExts), s.VideoExts),
            (nameof(AppSettings.ImageExts), s.ImageExts),
            (nameof(AppSettings.AudioExts), s.AudioExts),
            (nameof(AppSettings.InputIpcServer), s.InputIpcServer),
            (nameof(AppSettings.CacheDirectory), s.CacheDirectory),
            (nameof(AppSettings.WatchLaterDir), s.WatchLaterDir),
            (nameof(AppSettings.WatchLaterOptions), s.WatchLaterOptions),
            (nameof(AppSettings.IccCacheDir), s.IccCacheDir),
            (nameof(AppSettings.GpuShaderCacheDir), s.GpuShaderCacheDir),
            (nameof(AppSettings.Deinterlace), s.Deinterlace),
            (nameof(AppSettings.AspectRatio), s.AspectRatio),
            (nameof(AppSettings.Cscale), s.Cscale),
            (nameof(AppSettings.Tscale), s.Tscale),
            (nameof(AppSettings.LinearUpscaling), s.LinearUpscaling),
            (nameof(AppSettings.Dither), s.Dither),
            (nameof(AppSettings.Panscan), s.Panscan),
            (nameof(AppSettings.VideoUnscaled), s.VideoUnscaled),
            (nameof(AppSettings.BackgroundTileColor0), s.BackgroundTileColor0),
            (nameof(AppSettings.BackgroundTileColor1), s.BackgroundTileColor1),
            (nameof(AppSettings.BackgroundTileSize), s.BackgroundTileSize),
            (nameof(AppSettings.SubFontSize), s.SubFontSize),
            (nameof(AppSettings.SubDelay), s.SubDelay),
            (nameof(AppSettings.Speed), s.Speed),
            (nameof(AppSettings.SubPos), s.SubPos),
            (nameof(AppSettings.AudioLanguage), s.AudioLanguage),
            (nameof(AppSettings.SubtitleLanguage), s.SubtitleLanguage),
            (nameof(AppSettings.SubFilePaths), s.SubFilePaths),
            (nameof(AppSettings.SubHdrPeak), s.SubHdrPeak),
            (nameof(AppSettings.ImageSubsHdrPeak), s.ImageSubsHdrPeak),
            (nameof(AppSettings.ImageSubsVideoResolution), s.ImageSubsVideoResolution),
            (nameof(AppSettings.SubAssStyleOverrides), s.SubAssStyleOverrides),
            (nameof(AppSettings.SubColor), s.SubColor),
            (nameof(AppSettings.SubBackColor), s.SubBackColor),
            (nameof(AppSettings.SubBorderColor), s.SubBorderColor),
            (nameof(AppSettings.SubScaleSigns), s.SubScaleSigns),
            (nameof(AppSettings.SubAssUseVideoData), s.SubAssUseVideoData),
            (nameof(AppSettings.SubAssVideoAspectOverride), s.SubAssVideoAspectOverride),
            (nameof(AppSettings.SubAssVsfilterColorCompat), s.SubAssVsfilterColorCompat),
            (nameof(AppSettings.AudioDevice), s.AudioDevice),
            (nameof(AppSettings.ScreenshotDirectory), s.ScreenshotDirectory),
            (nameof(AppSettings.ScreenshotTemplate), s.ScreenshotTemplate),
            (nameof(AppSettings.SavePositionOnQuit), s.SavePositionOnQuit),
            (nameof(AppSettings.ResumePlayback), s.ResumePlayback),
            (nameof(AppSettings.ScreenshotFormat), s.ScreenshotFormat),
            (nameof(AppSettings.ScreenshotJpegQuality), s.ScreenshotJpegQuality),
            (nameof(AppSettings.ScreenshotJpegSourceChroma), s.ScreenshotJpegSourceChroma),
            (nameof(AppSettings.VideoSync), s.VideoSync),
            (nameof(AppSettings.VideoSyncMaxVideoChange), s.VideoSyncMaxVideoChange),
            (nameof(AppSettings.Interpolation), s.Interpolation),
            (nameof(AppSettings.CorrectDownscaling), s.CorrectDownscaling),
            (nameof(AppSettings.Scale), s.Scale),
            (nameof(AppSettings.DScale), s.DScale),
            (nameof(AppSettings.VideoRotate), s.VideoRotate),
            (nameof(AppSettings.Deband), s.Deband),
            (nameof(AppSettings.LinearDownscaling), s.LinearDownscaling),
            (nameof(AppSettings.SigmoidUpscaling), s.SigmoidUpscaling),
            (nameof(AppSettings.ToneMapping), s.ToneMapping),
            (nameof(AppSettings.DitherDepth), s.DitherDepth),
            (nameof(AppSettings.HrSeek), s.HrSeek),
            (nameof(AppSettings.HrSeekFramedrop), s.HrSeekFramedrop),
            (nameof(AppSettings.CacheOnDisk), s.CacheOnDisk),
            (nameof(AppSettings.TargetColorspaceHint), s.TargetColorspaceHint),
            (nameof(AppSettings.TargetColorspaceHintMode), s.TargetColorspaceHintMode),
            (nameof(AppSettings.TargetColorspaceHintStrict), s.TargetColorspaceHintStrict),
            (nameof(AppSettings.TargetPrim), s.TargetPrim),
            (nameof(AppSettings.TargetTrc), s.TargetTrc),
            (nameof(AppSettings.TargetPeak), s.TargetPeak),
            (nameof(AppSettings.GamutMappingMode), s.GamutMappingMode),
            (nameof(AppSettings.VideoOutputLevels), s.VideoOutputLevels),
            (nameof(AppSettings.VideoDecodeDirect), s.VideoDecodeDirect),
            (nameof(AppSettings.IccProfileAuto), s.IccProfileAuto),
            (nameof(AppSettings.IccProfile), s.IccProfile),
            (nameof(AppSettings.IccForceContrast), s.IccForceContrast),
            (nameof(AppSettings.IccCache), s.IccCache),
            (nameof(AppSettings.Icc3dlutSize), s.Icc3dlutSize),
            (nameof(AppSettings.DemuxerMaxBytes), s.DemuxerMaxBytes),
            (nameof(AppSettings.DemuxerMaxBackBytes), s.DemuxerMaxBackBytes),
            (nameof(AppSettings.GpuShaderCache), s.GpuShaderCache),
            (nameof(AppSettings.GlslShadersAppend), s.GlslShadersAppend),
            (nameof(AppSettings.AudioChannels), s.AudioChannels),
            (nameof(AppSettings.AudioGapless), s.AudioGapless),
            (nameof(AppSettings.AudioWaitOpen), s.AudioWaitOpen),
            (nameof(AppSettings.AudioBuffer), s.AudioBuffer),
            (nameof(AppSettings.AudioExclusive), s.AudioExclusive),
            (nameof(AppSettings.AudioPitchCorrection), s.AudioPitchCorrection),
            (nameof(AppSettings.AudioNormalizeDownmix), s.AudioNormalizeDownmix),
            (nameof(AppSettings.AudioFileAuto), s.AudioFileAuto),
            (nameof(AppSettings.AudioFilePaths), s.AudioFilePaths),
            (nameof(AppSettings.AudioDisplay), s.AudioDisplay),
            (nameof(AppSettings.AudioDelay), s.AudioDelay),
            (nameof(AppSettings.SubAssOverride), s.SubAssOverride),
            (nameof(AppSettings.SubBlur), s.SubBlur),
            (nameof(AppSettings.SubAuto), s.SubAuto),
            (nameof(AppSettings.SubFont), s.SubFont),
            (nameof(AppSettings.SubFontProvider), s.SubFontProvider),
            (nameof(AppSettings.SubFontFile), s.SubFontFile),
            (nameof(AppSettings.SubAssScaleWithWindow), s.SubAssScaleWithWindow),
            (nameof(AppSettings.BlendSubtitles), s.BlendSubtitles),
            (nameof(AppSettings.SubFallback), s.SubFallback),
            (nameof(AppSettings.SubCodePage), s.SubCodePage),
            (nameof(AppSettings.SubOutlineSize), s.SubOutlineSize),
            (nameof(AppSettings.SubShadowOffset), s.SubShadowOffset),
            (nameof(AppSettings.SubEmbeddedFonts), s.SubEmbeddedFonts),
            (nameof(AppSettings.SubUseMargins), s.SubUseMargins),
            (nameof(AppSettings.SubAssForceMargins), s.SubAssForceMargins),
            (nameof(AppSettings.StretchImageSubsToScreen), s.StretchImageSubsToScreen),
            (nameof(AppSettings.OsdFontSize), s.OsdFontSize),
            (nameof(AppSettings.OsdFont), s.OsdFont),
            (nameof(AppSettings.OsdColor), s.OsdColor),
            (nameof(AppSettings.OsdOutlineColor), s.OsdOutlineColor),
            (nameof(AppSettings.OsdPlayingMsg), s.OsdPlayingMsg),
            (nameof(AppSettings.OsdPlayingMsgDuration), s.OsdPlayingMsgDuration),
            (nameof(AppSettings.OsdBarWidth), s.OsdBarWidth),
            (nameof(AppSettings.OsdBarHeight), s.OsdBarHeight),
            (nameof(AppSettings.OsdBlur), s.OsdBlur),
            (nameof(AppSettings.OsdOutlineSize), s.OsdOutlineSize),
            (nameof(AppSettings.OsdFractions), s.OsdFractions),
            (nameof(AppSettings.OsdOnSeek), s.OsdOnSeek),
            (nameof(AppSettings.OsdDuration), s.OsdDuration),
            (nameof(AppSettings.CacheSecs), s.CacheSecs),
            (nameof(AppSettings.ScreenshotPngCompression), s.ScreenshotPngCompression),
            (nameof(AppSettings.ScreenshotPngFilter), s.ScreenshotPngFilter),
            (nameof(AppSettings.ScreenshotWebpQuality), s.ScreenshotWebpQuality),
            (nameof(AppSettings.ScreenshotWebpLossless), s.ScreenshotWebpLossless),
            (nameof(AppSettings.ScreenshotWebpCompression), s.ScreenshotWebpCompression),
            (nameof(AppSettings.ScreenshotJxlDistance), s.ScreenshotJxlDistance),
            (nameof(AppSettings.ScreenshotJxlEffort), s.ScreenshotJxlEffort),
            (nameof(AppSettings.ScreenshotAvifEncoder), s.ScreenshotAvifEncoder),
            (nameof(AppSettings.ScreenshotHighBitDepth), s.ScreenshotHighBitDepth),
            (nameof(AppSettings.ScreenshotTagColorspace), s.ScreenshotTagColorspace),
            (nameof(AppSettings.ScreenshotSw), s.ScreenshotSw),
            (nameof(AppSettings.VsrAutoEnabled), s.VsrAutoEnabled),
            (nameof(AppSettings.HdrAutoMode), s.HdrAutoMode),
            (nameof(AppSettings.SeekHoldEnabled), s.SeekHoldEnabled),
        })
        {
            if (ToCommand(key, value) is { } cmd)
            {
                run(cmd);
            }
        }
    }
}
