<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
        <WindowsSdkPackageVersion>10.0.26100.87</WindowsSdkPackageVersion>
        <RootNamespace>mpv_winrt_test</RootNamespace>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="10.0.1">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
        <PackageReference Include="NUnit" Version="4.6.1" />
        <PackageReference Include="NUnit.Analyzers" Version="4.14.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\mpv-winrt-projection\mpv-winrt-projection.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework" />
        <Using Include="System.Text.RegularExpressions" />
        <Using Include="System.Threading.Tasks" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\libs\bin\mpv-2.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="..\x64\Debug\mpv-winrt\mpv_winrt.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
