<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
        <WindowsSdkPackageVersion>10.0.26100.87</WindowsSdkPackageVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Platform>AnyCPU</Platform>
        <UseWinUI>true</UseWinUI>
        <CsWinRTIncludes>mpv_winrt</CsWinRTIncludes>
        <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
        <CsWinRTGenerateAotProjection>true</CsWinRTGenerateAotProjection>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.3.1">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.WindowsAppSDK.WinUI" Version="2.3.6">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\mpv-winrt\mpv-winrt.vcxproj">
            <PrivateAssets>all</PrivateAssets>
        </ProjectReference>
    </ItemGroup>

    <PropertyGroup>
        <NativeArch Condition="'$(NativeArch)' == ''">x64</NativeArch>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>mpv-winrt-projection</PackageId>
        <PackageVersion>0.3.0-prerelease</PackageVersion>
        <PackageAuthors>ikas</PackageAuthors>
        <PackageDescription>mpv-winrt-projection</PackageDescription>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" />
        <None Include="$(OutputPath)mpv-winrt-projection.dll" Pack="true" PackagePath="lib\$(TargetFramework)" />
        <None Include="..\$(NativeArch)\$(Configuration)\mpv-winrt\mpv_winrt.dll" Pack="true" PackagePath="runtimes\win-$(NativeArch)\native" />
        <None Include="..\libs\bin\mpv-2.dll" Pack="true" PackagePath="runtimes\win-$(NativeArch)\native" />
    </ItemGroup>
</Project>
