RIGHT            osd-msg-bar seek  2 relative+exact
LEFT             osd-msg-bar seek -2 relative+exact
UP               osd-msg add volume 2
DOWN             osd-msg add volume -2

SPACE            cycle pause

PGDWN            playlist-next
PGUP             playlist-prev

.                frame-step
,                frame-back-step

ENTER            show-progress
ESC              set fullscreen no

F1               script-binding stats/display-page-1-toggle
F2               script-binding stats/display-page-5-toggle
F3               script-binding stats/display-stats-toggle

F11              cycle fullscreen

#
# The "{discnav}" section is enabled only while a disc menu with a button
# highlight is actually on screen.
#
UP         {discnav} discnav up
DOWN       {discnav} discnav down
LEFT       {discnav} discnav left
RIGHT      {discnav} discnav right
ENTER      {discnav} discnav select
ESC        {discnav} discnav prev
BS         {discnav} discnav prev
MOUSE_MOVE {discnav} discnav mouse-move
MBTN_LEFT  {discnav} discnav mouse-click
Ctrl+m    discnav menu
Ctrl+M    discnav popup 
