#######
### Default
# gpu-shader-cache-dir=~~/cache/shaders_cache
# screenshot-dir=~~/screenshots
# osc=no
# idle=yes

# script-opts=select-populate_menu_data=yes
# load-select=yes
# input-default-bindings=yes
# input-media-keys=yes
# media-controls=yes

# reset-on-next-file=pause,ab-loop-a,ab-loop-b
# volume=50

# user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
# gpu-api=d3d11
# d3d11-output-mode=composition
# auto-window-resize=no
# force-window=yes
# d3d11-composition-size=1x1
#######

### mpvw
include=~~/mpvw.conf